name: "run"

chr: "1"
bin_size: 50e3 # in bp (e.g. 50e3 is 50kb)
genomic_range_enabled: false
genomic_range: [80e6,120e6] # in bp
# Interesting regions:
# 200e6-215e6
# 24e6-30e6 -> did for most experiments
# 195e6-240e6
# 45310e3-45803e3
# Gr1: 24e6-30e6
# Gr2: 24e6-40e6
# Gr3: 80e6-120e6

# GR1 - 24e6,30e6

do_logging: true
num_workers_encode: 'none'

visualization:
  visualize_edge_histogram : false
  visualize_edge_order_fits:
    power: false
    exponential: false
  visualize_genomic_dist : false
  visualize_dendogram: true
  verbose_labels: false
  visualize_diff_vs_undiff: false

data_adjustment:
  hyperedge_range:              [2, 100] # filter edge sizes to within this range

baseline: 'none' 